export default function TermsOfServicePage() {
  return (
    <div className="container-page" style={{ maxWidth: 760, paddingTop: 56, paddingBottom: 80 }}>
      <h1 style={{ fontSize: 30, fontWeight: 800, marginBottom: 6 }}>Terms of Service</h1>
      <p style={{ color: "var(--color-muted)", fontSize: 14, marginBottom: 36 }}>
        Last updated:{" "}
        {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
      </p>

      <Section title="1. Acceptance of Terms">
        By creating an account or using SentiTrack, you agree to these Terms of Service. If you do not agree,
        please do not use the platform. SentiTrack is a final-year academic project and is provided for
        educational and demonstration purposes.
      </Section>

      <Section title="2. Use of the Service">
        <ul style={{ paddingLeft: 20, lineHeight: 2, color: "var(--color-text)" }}>
          <li>You must be at least 13 years old to create an account.</li>
          <li>You are responsible for keeping your account credentials secure.</li>
          <li>You agree not to submit content that is illegal, harmful, or violates third-party rights.</li>
          <li>You agree not to attempt to reverse-engineer, scrape, or abuse the platform in any way.</li>
          <li>Each account is personal — you may not share or transfer it to another person.</li>
        </ul>
      </Section>

      <Section title="3. User Content">
        Comments and links you submit for sentiment analysis are processed transiently — they are not stored
        on our servers beyond the duration of the API request. Analysis results are saved locally in your
        browser only. You retain full ownership of any content you submit. By submitting content, you grant
        SentiTrack a temporary, non-exclusive right to process it solely for the purpose of generating your
        sentiment report.
      </Section>

      <Section title="4. Third-Party Authentication">
        SentiTrack offers optional sign-in through Google and Apple. By using these options, you also agree to
        the respective terms of those providers. SentiTrack only receives your name and email from these
        providers — never your password or payment details.
      </Section>

      <Section title="5. Accuracy of Results">
        Sentiment analysis results are generated by a machine learning model and are provided for informational
        purposes only. SentiTrack does not guarantee the accuracy, completeness, or fitness of these results
        for any particular business decision. Do not rely solely on automated sentiment scores for critical
        decisions.
      </Section>

      <Section title="6. Service Availability">
        SentiTrack is an academic project and is provided on an "as is" and "as available" basis. We do not
        guarantee uninterrupted availability and may update, suspend, or discontinue the service at any time
        without notice.
      </Section>

      <Section title="7. Intellectual Property">
        The SentiTrack name, logo, and UI design are the property of the project authors. You may not reproduce
        or redistribute them without permission. The underlying machine learning model is owned and operated by
        the respective team member and is subject to their own terms.
      </Section>

      <Section title="8. Limitation of Liability">
        To the maximum extent permitted by applicable law, SentiTrack and its authors shall not be liable for
        any indirect, incidental, special, or consequential damages arising from your use of the service,
        including but not limited to loss of data or business decisions made based on analysis results.
      </Section>

      <Section title="9. Account Termination">
        You may delete your account at any time from the Settings page. We reserve the right to suspend or
        terminate accounts that violate these terms.
      </Section>

      <Section title="10. Changes to These Terms">
        We may update these Terms of Service as the project evolves. Continued use after changes are posted
        constitutes acceptance of the updated terms. The date at the top of this page reflects the most recent
        update.
      </Section>

      <Section title="11. Contact">
        For any questions about these terms, reach us at:{" "}
        <strong>sentitrack.support@gmail.com</strong> · <strong>+977 981-2345678</strong> · Kathmandu, Nepal.
      </Section>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div className="card" style={{ padding: 28, marginBottom: 20 }}>
      <h2 style={{ fontSize: 16, fontWeight: 700, marginBottom: 14 }}>{title}</h2>
      <div style={{ fontSize: 14, lineHeight: 1.8, color: "var(--color-text)" }}>{children}</div>
    </div>
  );
}